apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: hc-feedback-hpa
    namespace: hc-feedback
    labels:
        app: hc-feedback-pipeline
        tier: frontend
spec:
    scaleTargetRef:
        apiVersion: apps/v1beta1
        kind: Deployment
        name: hc-feedback-pipeline
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 10
